sudo: required

services:
    - docker

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}

script:
    - export REPO=heriyanto/playtravis
    - sudo rm /usr/local/bin/docker-compose
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.8.1/docker-compose-$(uname -s)-$(uname -m)" > docker-compose
    - sudo chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin/
    - sudo docker-compose up -d --build
    - docker images
    - docker login -e=shell.heriyanto@gmail.com -u=heriyanto -p=P3zhK{EmzECB`~Ac
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - docker build -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
    - docker ps -a
    - docker logout
